export const investment_assets = [
  {
    index: 1,
    name: "High-Yield Savings Account",
    category: "Cash Savings",
    description:
      "FDIC-insured savings account offering higher interest rates than traditional accounts",
    smart_contract_address: "",
    imageURL: "/assetLogo/savings.png",
    marketCap: "500000",
    "12monthsChange": "+4.5",
    country: "USA",
    ticket: "HYS",
  },
  {
    index: 2,
    name: "US Treasury Bonds",
    category: "Bonds",
    description:
      "Government-backed fixed-income securities with various maturity periods",
    smart_contract_address: "",
    imageURL: "/assetLogo/treasury.png",
    marketCap: "25000000",
    "12monthsChange": "-2.1",
    country: "USA",
    ticket: "USB",
  },
  {
    index: 3,
    name: "Corporate AAA Bonds",
    category: "Bonds",
    description:
      "High-grade corporate bonds from established companies with excellent credit ratings",
    smart_contract_address: "",
    imageURL: "/assetLogo/corporate-bonds.png",
    marketCap: "10000000",
    "12monthsChange": "-1.8",
    country: "Global",
    ticket: "CAB",
  },
  {
    index: 4,
    name: "Apple Inc. (AAPL)", 
    category: "Stocks",
    description:
      "Common stock shares of Apple Inc., a leading technology company",
    smart_contract_address: "",
    imageURL: "/assetLogo/apple.png",
    marketCap: "2700000",
    "12monthsChange": "+21.5",
    country: "USA",
    ticket: "AAPL",
  },
  {
    index: 5,
    name: "Microsoft (MSFT)",
    category: "Stocks",
    description:
      "Common stock shares of Microsoft Corporation, a major software and cloud computing company",
    smart_contract_address: "",
    imageURL: "/assetLogo/msft.png",
    marketCap: "3000000",
    "12monthsChange": "+25.3",
    country: "USA",
    ticket: "MSFT",
  },
  {
    index: 6,
    name: "Vanguard S&P 500 ETF",
    category: "Funds",
    description:
      "Exchange-traded fund tracking the S&P 500 index of large-cap US stocks",
    smart_contract_address: "",
    imageURL: "/assetLogo/voo.png",
    marketCap: "1000000",
    "12monthsChange": "+18.2",
    country: "USA",
    ticket: "VOO",
  },
  {
    index: 7,
    name: "Bitcoin (BTC)",
    category: "Cryptocurrencies",
    description:
      "The first and largest cryptocurrency by market capitalization",
    smart_contract_address: "",
    imageURL: "/assetLogo/btc.png",
    marketCap: "1300000",
    "12monthsChange": "+62.4",
    country: "Global",
    ticket: "BTC",
  },
  {
    index: 8,
    name: "Ethereum (ETH)",
    category: "Cryptocurrencies",
    description:
      "Leading smart contract platform and second-largest cryptocurrency",
    smart_contract_address: "",
    imageURL: "/assetLogo/eth.png",
    marketCap: "400000",
    "12monthsChange": "+48.7",
    country: "Global",
    ticket: "ETH",
  },
  {
    index: 9,
    name: "Residential Real Estate Trust",
    category: "Real Estate",
    description: "Investment trust focused on residential property portfolios",
    smart_contract_address: "",
    imageURL: "/assetLogo/residential-reit.png",
    marketCap: "50000",
    "12monthsChange": "+8.3",
    country: "Hong Kong",
    ticket: "RET",
  },
  {
    index: 10,
    name: "Commercial REIT",
    category: "Real Estate",
    description:
      "Real Estate Investment Trust specializing in commercial properties",
    smart_contract_address: "",
    imageURL: "/assetLogo/commercial-reit.png",
    marketCap: "40000",
    "12monthsChange": "+5.2",
    country: "Dubai",
    ticket: "CRT",
  },
  {
    index: 11,
    name: "Money Market Fund",
    category: "Cash Savings",
    description:
      "Low-risk investment vehicle investing in short-term debt securities",
    smart_contract_address: "",
    imageURL: "/assetLogo/money-market.png",
    marketCap: "6000000",
    "12monthsChange": "+4.1",
    country: "USA",
    ticket: "MMF",
  },
  {
    index: 12,
    name: "Municipal Bonds",
    category: "Bonds",
    description: "Tax-exempt bonds issued by state and local governments",
    smart_contract_address: "",
    imageURL: "/assetLogo/muni-bonds.png",
    marketCap: "4000000",
    "12monthsChange": "-0.8",
    country: "USA",
    ticket: "MUB",
  },
  {
    index: 13,
    name: "Amazon.com (AMZN)",
    category: "Stocks",
    description:
      "Common stock shares of Amazon.com, leading e-commerce and cloud services provider",
    smart_contract_address: "",
    imageURL: "/assetLogo/amzn.png",
    marketCap: "1800000",
    "12monthsChange": "+32.1",
    country: "USA",
    ticket: "AMZN",
  },
  {
    index: 14,
    name: "Solana (SOL)",
    category: "Cryptocurrencies",
    description:
      "High-performance blockchain platform for decentralized applications",
    smart_contract_address: "",
    imageURL: "/assetLogo/sol.png",
    marketCap: "80000",
    "12monthsChange": "+280.5",
    country: "Global",
    ticket: "SOL",
  },
  {
    index: 15,
    name: "Fidelity Total Market Index Fund",
    category: "Funds",
    description:
      "Mutual fund providing broad exposure to the entire US stock market",
    smart_contract_address: "",
    imageURL: "/assetLogo/fidelity.png",
    marketCap: "500000",
    "12monthsChange": "+16.8",
    country: "USA",
    ticket: "FTMX",
  },
  {
    index: 16,
    name: "Industrial REIT",
    category: "Real Estate",
    description:
      "Real Estate Investment Trust focusing on industrial and logistics properties",
    smart_contract_address: "",
    imageURL: "/assetLogo/industrial-reit.png",
    marketCap: "30000",
    "12monthsChange": "+12.4",
    country: "Hong Kong",
    ticket: "IRT",
  },
  {
    index: 17,
    name: "Certificate of Deposit (CD)",
    category: "Cash Savings",
    description:
      "Time-deposit account with fixed interest rate and maturity date",
    smart_contract_address: "",
    imageURL: "/assetLogo/cd.png",
    marketCap: "200000",
    "12monthsChange": "+4.8",
    country: "USA",
    ticket: "CDS",
  },
  {
    index: 18,
    name: "Google (GOOGL)",
    category: "Stocks",
    description:
      "Common stock shares of Alphabet Inc., parent company of Google",
    smart_contract_address: "",
    imageURL: "/assetLogo/googl.png",
    marketCap: "2200000",
    "12monthsChange": "+28.7",
    country: "USA",
    ticket: "GOOG",
  },
  {
    index: 19,
    name: "Cardano (ADA)",
    category: "Cryptocurrencies",
    description:
      "Proof-of-stake blockchain platform with focus on sustainability",
    smart_contract_address: "",
    imageURL: "/assetLogo/ada.png",
    marketCap: "20000",
    "12monthsChange": "+32.4",
    country: "Global",
    ticket: "ADA",
  },
  {
    index: 20,
    name: "iShares Global REIT ETF",
    category: "Real Estate",
    description:
      "Exchange-traded fund investing in real estate companies worldwide",
    smart_contract_address: "",
    imageURL: "/assetLogo/global-reit.png",
    marketCap: "5000",
    "12monthsChange": "+7.2",
    country: "Singapore",
    ticket: "GRT",
  },
];
